In [2]:
from sklearn import datasets
digits =datasets.load_digits()

In [3]:
digits.data.shape

(1797, 64)

In [4]:
training_data = digits.data[:1000]
training_target = digits.target[:1000]

In [5]:
testing_data = digits.data[1000:]
testing_target = digits.target[1000:]

In [7]:
print(training_data.shape)
print(training_target.shape)
print(testing_data.shape)
print(testing_target.shape)

(1000, 64)
(1000,)
(797, 64)
(797,)


In [113]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(training_data,training_target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [117]:
import numpy as np
predicted_result = neigh.predict(testing_data)
correct = np.sum(predicted_result == testing_target)
total = testing_data.shape[0]
accuracy = correct/total*100
print(correct)
print(total)
print(accuracy)

#another way to show accuracy by using library
from sklearn.metrics import accuracy_score
print(accuracy_score(testing_target,predicted_result))

767
797
96.2358845671
0.962358845671


In [118]:
from sklearn.metrics import confusion_matrix
a = confusion_matrix(testing_target,predicted_result)

In [111]:
print(a.shape)
print(a)

(10, 10)
[[78  0  0  0  1  0  0  0  0  0]
 [ 0 79  0  0  0  0  0  0  1  0]
 [ 1  0 73  3  0  0  0  0  0  0]
 [ 0  0  1 73  0  1  0  2  2  0]
 [ 0  0  0  0 78  0  0  1  0  4]
 [ 0  0  0  0  0 81  1  0  0  0]
 [ 0  0  0  0  0  0 80  0  0  0]
 [ 0  0  0  0  0  0  0 80  0  0]
 [ 0  2  1  0  0  0  0  0 73  0]
 [ 0  0  0  3  0  3  0  0  1 74]]
